In [1]:
from qutip import *
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display, display_latex

## Display an Object or Matrix in QuTiP

In [21]:
obj = Qobj([[1, 0], [0, 1j]])

display(obj)

display(obj.dag())

Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=Dense, isherm=False
Qobj data =
[[1.+0.j 0.+0.j]
 [0.+0.j 0.+1.j]]

Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=Dense, isherm=False
Qobj data =
[[1.-0.j 0.-0.j]
 [0.-0.j 0.-1.j]]

## Create a ket vector in QuTiP

In [12]:
vac = basis(2, 0)

display(vac)

Quantum object: dims=[[2], [1]], shape=(2, 1), type='ket', dtype=Dense
Qobj data =
[[1.]
 [0.]]

## Create a density matrix in QuTiP

In [28]:
ket = basis(2, 0)
display(ket)

bra = basis(2, 1).dag()
display(bra)

display(ket * bra)

Quantum object: dims=[[2], [1]], shape=(2, 1), type='ket', dtype=Dense
Qobj data =
[[1.]
 [0.]]

Quantum object: dims=[[1], [2]], shape=(1, 2), type='bra', dtype=Dense
Qobj data =
[[0. 1.]]

Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=Dense, isherm=False
Qobj data =
[[0. 1.]
 [0. 0.]]