In [2]:
from qutip import *
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display, display_latex

## Display an Object or Matrix in QuTiP

In [3]:
obj = Qobj([[1, 0], [0, 1j]])

display(obj)

display(obj.dag())

Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=Dense, isherm=False
Qobj data =
[[1.+0.j 0.+0.j]
 [0.+0.j 0.+1.j]]

Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=Dense, isherm=False
Qobj data =
[[1.-0.j 0.-0.j]
 [0.-0.j 0.-1.j]]

## Create a ket vector in QuTiP

In [4]:
vac = basis(2, 0)

display(vac)

Quantum object: dims=[[2], [1]], shape=(2, 1), type='ket', dtype=Dense
Qobj data =
[[1.]
 [0.]]

## Create a density matrix in QuTiP

In [5]:
ket = basis(2, 0)
display(ket)

bra = basis(2, 1).dag()
display(bra)

display(ket * bra)

Quantum object: dims=[[2], [1]], shape=(2, 1), type='ket', dtype=Dense
Qobj data =
[[1.]
 [0.]]

Quantum object: dims=[[1], [2]], shape=(1, 2), type='bra', dtype=Dense
Qobj data =
[[0. 1.]]

Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=Dense, isherm=False
Qobj data =
[[0. 1.]
 [0. 0.]]

In [16]:
psi = basis(4,2)
display(psi)

rho = psi * psi.dag()

display(rho)

Quantum object: dims=[[4], [1]], shape=(4, 1), type='ket', dtype=Dense
Qobj data =
[[0.]
 [0.]
 [1.]
 [0.]]

Quantum object: dims=[[4], [4]], shape=(4, 4), type='oper', dtype=Dense, isherm=True
Qobj data =
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]]

In [33]:
mat = np.eye(4)
np.trace(mat)

mat2 = np.random.randint(0,2, (4,4))
mat2

out=0
for i in range(10000):
    out += np.trace( np.random.randint(0, 2, (4,4)) )

print(out/10000)

2.0076
